/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmEmpleado.java
 *
 * Created on 10-oct-2011, 9:24:06
 */
package apiformularios.form;

import api.dom.Empleado;
import api.dom.Utilitaria;
import api.gest.GestEmpleado;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class FrmEmpleado extends javax.swing.JInternalFrame {

    /** Creates new form FrmEmpleado */
    public FrmEmpleado() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        this.txtNumero.setText(String.valueOf(GestEmpleado.getInstance().devolverUltimoNum()));
        Utilitaria.listarEmpleados((DefaultTableModel) jTable2.getModel());
        this.btnAgregar.setEnabled(false);
        
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboxCargo = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        btnAgregar1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtfingreso = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setTitle("Empleados");
        setMaximumSize(new java.awt.Dimension(580, 570));
        setMinimumSize(new java.awt.Dimension(580, 570));
        setNextFocusableComponent(txtNombre1);
        setNormalBounds(new java.awt.Rectangle(0, 0, 650, 570));
        setPreferredSize(new java.awt.Dimension(650, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Numero :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Nombre :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText(" *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Telefono :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("C.I :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        txtNumero.setEditable(false);
        txtNumero.setFocusable(false);
        txtNumero.setNextFocusableComponent(txtNombre1);
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, -1));

        txtDireccion.setNextFocusableComponent(btnAgregar1);
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 180, -1));

        txtTelefono.setNextFocusableComponent(txtCedula);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 180, -1));

        txtCedula.setNextFocusableComponent(txtDireccion);
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 180, -1));

        btnAgregar.setText("Modificar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 80, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 80, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("Fec Ing :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setText("Cargo :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        cboxCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chofer", "Ayudante", "Empresa contratada" }));
        cboxCargo.setNextFocusableComponent(txtTelefono);
        cboxCargo.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(cboxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 170, -1));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero ", "Nombre", "Direccion", "Telefono", "C.I", "Ingreso", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 630, 310));

        jPanel1.setBackground(new java.awt.Color(153, 180, 209));

        jLabel6.setBackground(new java.awt.Color(51, 255, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel6.setText("Empleados");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setText("Buscar");
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 90, 40));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 40));

        txtNombre1.setNextFocusableComponent(txtfingreso);
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 170, -1));

        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        btnAgregar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregar1KeyPressed(evt);
            }
        });
        getContentPane().add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 80, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 2, 12));
        jLabel21.setText("Campos Obligatorios (*)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        txtfingreso.setNextFocusableComponent(cboxCargo);
        getContentPane().add(txtfingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 170, -1));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 30, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setText("Direccion :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 12));
        jLabel10.setText("Campos Obligatorios (*)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 140, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel11.setText(" *");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setText(" *");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        try {

            Date date = new Date();
            date = (txtfingreso.getDate());
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String fecha = dateFormat.format(date);
            Empleado objEmp = new Empleado(txtCedula.getText(), fecha, cboxCargo.getSelectedItem().toString(), Integer.parseInt(txtNumero.getText()), txtNombre1.getText(), txtDireccion.getText(), txtTelefono.getText());
            GestEmpleado.getInstance().modificarEmpleado(objEmp);
            txtNombre1.setText("");
            txtCedula.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtNumero.setText(String.valueOf(GestEmpleado.getInstance().devolverUltimoNum()));
            Utilitaria.limpiarJtables((DefaultTableModel) jTable2.getModel());
            Utilitaria.listarEmpleados((DefaultTableModel) jTable2.getModel());
            JOptionPane.showMessageDialog(rootPane, "Empleado modificado con exito");
            this.btnAgregar1.setEnabled(true);
            this.btnAgregar.setEnabled(false);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un empleado de la lista");
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (jTable2.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un empleado");
        } else {
            String x = (String.valueOf(this.jTable2.getValueAt(jTable2.getSelectedRow(), 0)));
            int numero = Integer.parseInt(x);
            /*if (AppAdministracion.getInstance().buscarSiLocalTieneOperador(numero) == false) {
            JOptionPane.showMessageDialog(null, "ALGUN LOCAL ESTA ASOCIADO AL OPERADOR,\n IMPOSIBLE DE ELIMINAR", "Fatal Error", JOptionPane.ERROR_MESSAGE);
            } else {*/
            if (GestEmpleado.getInstance().bajaEmpleado(numero) == true) {
                JOptionPane.showMessageDialog(rootPane, "Empleado eliminado correctamente");
                this.btnAgregar1.setEnabled(true);
                this.btnAgregar.setEnabled(false);
                this.txtNumero.setText(String.valueOf(GestEmpleado.getInstance().devolverUltimoNum()));
                this.txtNombre1.setText("");
                this.txtCedula.setText("");
                this.txtDireccion.setText("");
                this.txtTelefono.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el empleado. \n El registro esta en alguna factura");
            
            }
            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            for (int i = 0; i < modelo.getRowCount();) {
                modelo.removeRow(i);
            }
            for (Empleado obje : GestEmpleado.getInstance().devolverEmpleado()) {
                Object[] objOp = {obje.getpNumero(), obje.getpNombre(), obje.getpDireccion(), obje.getpTelefono(), obje.geteCedulaIdentidad(), obje.geteFechaIngreso(), obje.geteCargo()};
                modelo.addRow(objOp);
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        txtNombre1.setText(String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 1)));
        txtCedula.setText(String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 4)));
        txtDireccion.setText(String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 2)));
        txtTelefono.setText(String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 3)));
        txtNumero.setText(String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 0)));
        cboxCargo.setSelectedItem(jTable2.getValueAt(jTable2.getSelectedRow(), 6));
        this.txtfingreso.setDate(Utilitaria.convertirStringDate(String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 5))));
        //txtfingreso.sets

    }//GEN-LAST:event_jTable2MouseClicked

private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
// TODO add your handling code here:
    try {
        if ("".equals(txtNombre1.getText())) {
            JOptionPane.showMessageDialog(null, "Falto ingresar algun dato. \n Recuerde que los datos obligatorios son los datos de la columna de la izquierda");
        } else {
            Date date = new Date();
            date = (txtfingreso.getDate());
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String fecha = dateFormat.format(date);
            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            for (int i = 0; i < modelo.getRowCount();) {
                modelo.removeRow(i);
            }
            if ("".equals(txtTelefono.getText())) {
                txtTelefono.setText("No ingreso");
            } else if ("".equals(txtDireccion.getText())) {
                txtDireccion.setText("No ingreso");
            } else if ("".equals(txtCedula.getText())) {
                txtCedula.setText("No ingreso");
            }
            Empleado objEmp = new Empleado(txtCedula.getText(), fecha, cboxCargo.getSelectedItem().toString(), Integer.parseInt(txtNumero.getText()), txtNombre1.getText(), txtDireccion.getText(), txtTelefono.getText());
            GestEmpleado.getInstance().altaEmpleado(objEmp);
            this.txtNumero.setText(String.valueOf(GestEmpleado.getInstance().devolverUltimoNum()));
            for (Empleado obje : GestEmpleado.getInstance().devolverEmpleado()) {
                Object[] objOp = {obje.getpNumero(), obje.getpNombre(), obje.getpDireccion(), obje.getpTelefono(), obje.geteCedulaIdentidad(), obje.geteFechaIngreso(), obje.geteCargo()};
                modelo.addRow(objOp);
            }
        }
        this.txtNombre1.setText("");
        this.txtCedula.setText("");
        this.txtDireccion.setText("");
        this.txtTelefono.setText("");
    } catch (NullPointerException a) {
        JOptionPane.showMessageDialog(rootPane, "Selecione la fecha de ingreso");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Hubo un error interno mientras se agregaba el empleado. \nSi el problema persiste comuniquese a W.O.R.A inc");
    }
}//GEN-LAST:event_btnAgregar1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    this.btnAgregar1.setEnabled(true);
    this.btnAgregar.setEnabled(false);
    this.txtNumero.setText(String.valueOf(GestEmpleado.getInstance().devolverUltimoNum()));
    this.txtNombre1.setText("");
    this.txtCedula.setText("");
    this.txtDireccion.setText("");
    this.txtTelefono.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
    // TODO add your handling code here:
    try {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);
        String nombre = txtNombre.getText();
        int i = nombre.length();
        String nombre2;
        for (Empleado obje : GestEmpleado.getInstance().devolverEmpleado()) {
            nombre2 = obje.getpNombre();
            String cortado = nombre2.substring(0, i);
            if (cortado.equalsIgnoreCase(nombre)) {
                Object[] objcli = {obje.getpNumero(), obje.getpNombre(), obje.getpDireccion(), obje.getpTelefono(), obje.geteCedulaIdentidad(), obje.geteFechaIngreso(), obje.geteCargo()};
                modelo.addRow(objcli);
            }
        }
    } catch (Exception e) {
    }
}//GEN-LAST:event_txtNombreKeyReleased

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
        this.btnAgregar1.setEnabled(false);
        this.btnAgregar.setEnabled(true);
    }//GEN-LAST:event_jTable2MousePressed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed
 
    private void btnAgregar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregar1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              btnAgregar1ActionPerformed(null);              
          }
        
    }//GEN-LAST:event_btnAgregar1KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox cboxCargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefono;
    private com.toedter.calendar.JDateChooser txtfingreso;
    // End of variables declaration//GEN-END:variables
}
